language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21

before_install:
 - chmod +x gradlew

script: ./gradlew testRelease jacocoTestReport assembleRelease

